name: First Workflow
on: workflow_dispatch #manual trigger
jobs:
  first-job: #job name
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run:  ecoh "Hello World"
      - name: PRint goodbye
        run: echo "Done - bye!"
  

